In [1]:
import numpy as np

# Creating Arrays

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [5]:
a = np.array([1,2,3,5,7,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

# Multi-Dimensional Arrays

In [9]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [37]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

# Randomly Generated Arrays

In [12]:
np.random.seed(42)
np.random.rand(5,2) # Uniform distribution between 0-1

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452],
       [0.05808361, 0.86617615],
       [0.60111501, 0.70807258]])

# Element-wise Operations

In [14]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [15]:
a + 1

array([1, 2, 3, 4, 5])

In [31]:
b = 10 + (a * 2)
b

array([10, 12, 14, 16, 18])

In [19]:
a+b

array([10, 13, 16, 19, 22])

## Comparison Operations

In [21]:
a >= 2

array([False, False,  True,  True,  True])

In [32]:
b[1:3] = 0
a>b

array([False,  True,  True, False, False])

In [33]:
a[a>b]

array([1, 2])

# Summarizing Ops

In [34]:
a.std()

np.float64(1.4142135623730951)

In [35]:
a.sum() #etc..

np.int64(10)

In [36]:
np.dot(a,b)

np.int64(120)

In [38]:
a = [1,2,3]
np.matmul(n,a)
# or .dot again. Numpy knows since its 2D Array

array([14, 32, 50])

In [39]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
# Square matrix needed for inverse
# Inverse doesnt exist for n but get the idea.
# n x n(inv) = I (eye)
np.linalg.inv(n)

LinAlgError: Singular matrix